CXX = g++
CXXFLAGS = -std=c++11 -Wall -Wextra -I/opt/homebrew/include
LDFLAGS = -L/opt/homebrew/lib -lssl -lcrypto

TARGET = des_create_key
all: des_create_key

des_create_key: des_create_key.cpp
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

create: des_create_key

clean:
	rm -f des_create_key
