CXX = g++
CXXFLAGS = -std=c++11 -Wall -Wextra -I/opt/homebrew/include
LDFLAGS = -L/opt/homebrew/lib -lssl -lcrypto

TARGET = aes_create_key
all: $(TARGET)

$(TARGET): aes_create_key.cpp
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

create: $(TARGET)

clean:
	rm -f $(TARGET)
