CC=g++
CFLAGS=-Wall -Wextra -std=c++11 -I/opt/homebrew/opt/openssl@3/include
LIBS=-L/opt/homebrew/opt/openssl@3/lib -lssl -lcrypto

seed_create_key: seed_create_key.cpp
	$(CC) $(CFLAGS) -o seed_create_key seed_create_key.cpp $(LIBS)

create: seed_create_key
	./seed_create_key

clean:
	rm -f seed_create_key seed_key.bin seed_iv.bin

.PHONY: create clean