CC = gcc
CFLAGS = -Wall -O2 -I/opt/homebrew/include
LDFLAGS = -L/opt/homebrew/lib -lssl -lcrypto
TARGET = create_des_key
all: create_des_key

create_des_key: create_des_key.c
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

clean:
	rm -f create_des_key
